services:
  master:
    container_name: master
    build:
      context: ./master-config
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: bestportal
    volumes:
      - ./master-data:/var/lib/mysql
      - ./forquery:/forquery
    ports:
      - "3306:3306"

  slave:
    container_name: slave
    build:
      context: ./slave-config
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3306"
    depends_on:
      - master

networks:
  default:
    driver: bridge
